### ISSUE TITLE
Installation ce_navigation in Contao Bata 3.1.RC1

### ISSUE THREAD

**Issue by ciaobello** [hofff/contao-ce-navigation#4] opened 2012-08-14 02:50 UTC
Fatal error: Call to a member function tableExists() on a non-object in ...\system\modules\ce_navigation\config\runonce.php on line 76

When i try to add an article i get the following Error:

Fatal error: Uncaught exception Exception with message Query error: Unknown column 'navigation_article' in 'field list' (INSERT INTO tl_content (type, sortOrder, mooType, perRow, com_order, com_template, navigation_article, navigation_min_level, navigation_max_level, pid, sorting, ptable, tstamp) VALUES ('text', 'ascending', 'start', 4, 'ascending', 'com_default', 'main', '1', '6', 1, 384, 'tl_article', 0)) thrown in ...\system\modules\core\library\Contao\Database\Statement.php on line 317
#0 ...\system\modules\core\library\Contao\Database\Statement.php(261): Contao\Database\Statement->query()
#1 ...\system\modules\core\drivers\DC_Table.php(639): Contao\Database\Statement->execute()
#2 ...\system\modules\core\classes\Backend.php(382): Contao\DC_Table->create()
#3...\contao\main.php(121): Contao\Backend->getBackendModule('article')
#4 ...\contao\main.php(322): Main->run()
#5 {main}

(I was trying to make a one-page and use ce_navigation as a anchor navigation)

It would be really great when you could also talk in your screen-cast about contao3. Even if it is still in Beta station, people should now start to use it and debug problems.  I would like to see a screen-cast about the new features in C3.

Thanks in advance for your attention ;-)
ciaobello

**Comment by dmolineus** [comment] 2018-11-08 13:23
Duplicate of #5.

**Closed by dmolineus** 2018-11-08 13:23 UTC
Labels: duplicate
