### ISSUE TITLE
Headers of invisible article should not be display

### ISSUE THREAD

**Issue by falkoschumann** [hofff/contao-ce-navigation#14] opened 2014-03-21 14:58 UTC
If I set the content element self invisible the entry in table of content does not display. this is expected behavior.

If I set a article invisible the table of content display the headers from its content elements. This is unexpected behavior.

I think the ce-navigation module should ignore content elements of invisible articles, because links inside table of content without visible target confuse the user.

**Comment by dmolineus** [comment] 2018-11-08 12:40
We're currently working on migrating this extension to Contao 4. Gonna be fixed there.

https://github.com/hofff/contao-ce-navigation/blob/b8b32cd1a202fb8f471b42713e83ccf992be4d90/src/Navigation/Query/ItemsInColumnQuery.php#L23

**Comment by dmolineus** [comment] 2018-11-08 12:46
Duplicate of #7

**Closed by dmolineus** 2018-11-08 12:46 UTC
Labels: bug, duplicate
